name: Build and push


on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: Docker build
      run: |
        hostnamectl   

jobs:
  build-and-push-2:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: Docker build-2
      run: |
        hostnamectl   

jobs:
  build-and-push-3:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: Docker build-3
      run: |
        hostnamectl                   