name: Build and push


on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the repository
      uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secrete-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      id: login-ECR
      uses: aws-actions/amazon-ecr-login@v2      

    - name: Docker build
      run: | 
        echo "${{ vars.ENV_FILE }}" > .env
        cat .env
        docker build -t my-movieapp-backend:latest .

    - name: Docker push
      run: |
        docker tag movieapp_backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/movieapp_backend:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/movieapp_backend:latest